### ISSUE TITLE
Modal dialog not working: undefined function

### ISSUE THREAD

**Issue by joskuijpers** [makeusabrew/bootbox#298]
Hi!

I am using Bootstrap 3.2, angular-bootstrap 0.11.0 and angular 1.2.21.
I simply installed bootbox using bower install (4.3.0), and tried using

`bootbox.alert('Hello World!');`

This is what I get:

```
TypeError: undefined is not a function
    at Object.exports.dialog (http://localhost:3000/bower_components/bootbox/bootbox.js:689:16)
    at Object.exports.alert (http://localhost:3000/bower_components/bootbox/bootbox.js:307:24)
    at Scope.$scope.remove (http://localhost:3000/........./MY-controller.js:89:21)
    at http://localhost:3000/bower_components/angular/angular.js:10795:21
    at http://localhost:3000/bower_components/angular/angular.js:19036:17
    at Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:12632:28)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:12730:23)
    at HTMLButtonElement.<anonymous> (http://localhost:3000/bower_components/angular/angular.js:19035:21)
    at HTMLButtonElement.jQuery.event.dispatch (http://localhost:3000/bower_components/jquery/dist/jquery.js:4409:9)
    at HTMLButtonElement.elemData.handle (http://localhost:3000/bower_components/jquery/dist/jquery.js:4095:28) angular.js:10023
```

The 'dialog' variable, where the modal function is called on, does indeed not contain such function.

What is going on here? Might it be the angular ui bootstrap package?

Hope to hear what the troubles might be. I am wanting to use bootbox for error display and removal-confirmation.

**Comment by EvanCarroll** [comment]
Can we better check for the existence of Bootstrap.js? I mean, this will never be "hot" code. It would make more sense not to have everyone bit by this.
